version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Building web app
      - mkdir output
      - cp index.html output/
artifacts:
  files:
    - output/index.html

